# Generated by Django 5.0.7 on 2024-08-29 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0002_symptom_usersymptom"),
    ]

    operations = [
    # Comment out the CreateModel operation if the table already exists
    # migrations.CreateModel(
    #     name="Disease",
    #     fields=[
    #         ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
    #         ("name", models.CharField(max_length=100, unique=True)),
    #         ("description", models.TextField(default="")),
    #         ("symptoms", models.ManyToManyField(to="health_app.symptom")),
    #     ],
    # ),
    # Other operations...
]