# Generated by Django 5.0.7 on 2024-08-29 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0003_symptom_severity_alter_symptom_name_disease_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="symptom",
            name="severity",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(default="")),
                ("symptoms", models.ManyToManyField(to="health_app.symptom")),
            ],
        ),
        migrations.CreateModel(
            name="UserSymptomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("symptoms", models.ManyToManyField(to="health_app.symptom")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserSymptom",
        ),
    ]
