# Generated by Django 3.2.25 on 2024-09-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_symptom_severity_alter_symptom_name_disease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='severity',
        ),
    ]
